version: '3.7' 

volumes:
  orderer.vaahan.com:
  peer0.tnrto.vaahan.com:
  peer0.klrto.vaahan.com:
  peer0.knrto.vaahan.com:


networks:
  automobile:
    name: fabric_autoledger

services:

  orderer.vaahan.com:
    container_name: orderer.vaahan.com
    image: hyperledger/fabric-orderer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.vaahan.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/vaahan.com/orderers/orderer.vaahan.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/vaahan.com/orderers/orderer.vaahan.com/tls/:/var/hyperledger/orderer/tls
      - orderer.vaahan.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - automobile

  couchdb0:
    container_name: couchdb0
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - automobile

  peer0.tnrto.vaahan.com:
    container_name: peer0.tnrto.vaahan.com
    image: hyperledger/fabric-peer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_autoledger
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.tnrto.vaahan.com
      - CORE_PEER_ADDRESS=peer0.tnrto.vaahan.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.tnrto.vaahan.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.tnrto.vaahan.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.tnrto.vaahan.com:7051
      - CORE_PEER_LOCALMSPID=tnrtoMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.tnrto.vaahan.com:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0tnrto"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/tnrto.vaahan.com/peers/peer0.tnrto.vaahan.com:/etc/hyperledger/fabric
      - peer0.tnrto.vaahan.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    depends_on:
      - couchdb0
    networks:
      - automobile

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    networks:
      - automobile

  peer0.klrto.vaahan.com:
    container_name: peer0.klrto.vaahan.com
    image: hyperledger/fabric-peer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_autoledger
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.klrto.vaahan.com
      - CORE_PEER_ADDRESS=peer0.klrto.vaahan.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.klrto.vaahan.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.klrto.vaahan.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.klrto.vaahan.com:9051
      - CORE_PEER_LOCALMSPID=klrtoMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.klrto.vaahan.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0klrto"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/klrto.vaahan.com/peers/peer0.klrto.vaahan.com:/etc/hyperledger/fabric
      - peer0.klrto.vaahan.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 9445:9445
    depends_on:
      - couchdb1
    networks:
      - automobile

  couchdb2:
      container_name: couchdb2
      image: couchdb:3.3.2
      labels:
        service: hyperledger-fabric
      environment:
        - COUCHDB_USER=admin
        - COUCHDB_PASSWORD=adminpw
      ports:
        - "9984:5984"
      networks:
        - automobile

  peer0.knrto.vaahan.com:
      container_name: peer0.knrto.vaahan.com
      image: hyperledger/fabric-peer:2.5.4
      labels:
        service: hyperledger-fabric
      environment:
        # - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
        #Generic peer variables
        - FABRIC_LOGGING_SPEC=INFO
        #- FABRIC_LOGGING_SPEC=DEBUG
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_autoledger
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
        # Peer specific variables
        - CORE_PEER_ID=peer0.knrto.vaahan.com
        - CORE_PEER_ADDRESS=peer0.knrto.vaahan.com:11051
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
        - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
        - CORE_PEER_CHAINCODEADDRESS=peer0.knrto.vaahan.com:11052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.knrto.vaahan.com:11051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.knrto.vaahan.com:11051
        - CORE_PEER_LOCALMSPID=knrtoMSP
        - CORE_OPERATIONS_LISTENADDRESS=peer0.knrto.vaahan.com:9446
        - CORE_METRICS_PROVIDER=prometheus
        - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0knrto"}
        - CORE_CHAINCODE_EXECUTETIMEOUT=300s  
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      depends_on:
        - couchdb2    
      volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock      
        - ../organizations/peerOrganizations/knrto.vaahan.com/peers/peer0.knrto.vaahan.com:/etc/hyperledger/fabric        
        - peer0.knrto.vaahan.com:/var/hyperledger/production
      working_dir: /root
      command: peer node start
      ports:
        - 11051:11051
        - 9446:9446
      networks:
        - automobile

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.4
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
    depends_on:
      - peer0.tnrto.vaahan.com
      - peer0.klrto.vaahan.com
    networks:
      - automobile
